[package]
name = "dstui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3.31"
reqwest = { version = "*", features = ["json", "cookies", "cookie_store"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
humantime = "2.2.0"
chrono = { version = "0.4.40", features = ["serde"] }
dirs = "6.0.0"
toml = "0.8.22"
