[package]
name = "dstui"
version = "0.2.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3.31"
reqwest = { version = "0.11.27", features = [
  "json",
  "cookies",
  "cookie_store",
  "multipart",
  "stream",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.15"
humantime = "2.2.0"
chrono = { version = "0.4.40", features = ["serde"] }
dirs = "6.0.0"
toml = "0.8.22"
clipboard-rs = "0.2.4"
